on: 
  push:
     branches:
       - main
  pull_request:
     branches:
      - dev
    
jobs:
  shell-commands:
    runs-on: ubuntu-latest
    steps:
     - name: echo
       run: echo "hello world" 
     - name: multi-lined
       run: |
         ls -a  
         pwd
         npm -v

  python-commands:
    runs-on: ubuntu-latest
    steps:
     - name: python import
       run:
         import platform
         print(platform.processor())
       shell: python       
