on: 
  push:
     branches:
       - main
  pull_request:
     branches:
      - dev
    
jobs:
  shell-commands:
    runs-on: ubuntu-latest
    steps:
     - name: echo
       run: echo "hello world" 
     - name: multi-line
       run: |
         ls -a  
         pwd
         npm -v
