on: 
  push:
     branches:
       - main
  pull_request:
     branches:
      - dev
    
jobs:
  shell-commands:
    runs-on: ubuntu-latest
    steps:
     - name: echo
       run: echo "hello people" 
     - name: multi-line
       run: |
         ls -a  
         pwd
         npm -v

  python-commands:
    needs: shell-commands
    runs-on: ubuntu-latest
    steps:
     - name: python import
       run: |
         import platform
         print(platform.processor())
       shell: python       
  Windows-commands:
    runs-on: windows-latest
    steps:
    - name: Directory
      run: Get-location
    - name: Get Directory
      run: pwd
      shell: bash   